variables:
  buildConfiguration: 'Release'

jobs:
- job: BuildAndRunCodeAnalysis
  displayName: Build and run code analysis
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build solution and run code analysis
    inputs:
      command: build
      projects: '**\Atata.sln'
      arguments: -c $(buildConfiguration) /p:RunCodeAnalysis=true /warnaserror

- job: BuildAndRunTestsNet45
  displayName: Build and run tests using .NET 4.5 on Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build solution
    inputs:
      command: build
      projects: '**\Atata.sln'
      arguments: -c $(buildConfiguration)
  - task: VSTest@2
    displayName: Run tests
    timeoutInMinutes: 30
    continueOnError: true
    inputs:
      testFilterCriteria: TestCategory!=Unstable
      testAssemblyVer2: |
        **\*.Tests*.dll
        !**\obj\**
  - task: PublishPipelineArtifact@0
    displayName: Publish test results
    inputs:
      artifactName: Test results
      targetPath: src/Atata.Tests/bin/$(buildConfiguration)/net45/Logs